### ISSUE TITLE
Why hiera_conf uses replace = false?

### ISSUE THREAD

**Issue by tobru** [nesi/puppet-puppet#19]
Why are you setting `replace => false` on `file{'hiera_conf':`? Because when doing this, you can't change the hiera config later by puppet.

**Comment by Aethylred** [comment]
This was intentional, this module only wanted to do enough to suppress the warning about there being no Hiera config during a puppet run, so all this module does is make sure the file exists. It may need to be removed, or be switchable.

I never intended to manage the content of Hiera as we use it to hold sensitive information _outside_ the puppet configuration which will allow us to let more people, including those outside the team, view our puppet configuration as it'll be clear of passwords, salts, certificates, and user details. We put the hiera data into `.gitignore` for our manifest, then use git on the hiera data directory and put it in a private repository. We're not quite 100% on that yet.

**Comment by tobru** [comment]
I was a bit confused about this. When configuring something through Puppet, I normally expect that I can change it afterwards. We are also keeping the hieradata in a separate repository. And we are using hiera to actually configure hiera:

```
puppet::hiera::hiera_config_content: |
  ---
  :backends:
    - yaml
  :hierarchy:
    - "nodes/%%{}{::clientcert}"
    - "roles/%%{}{::role}"
    - "locations/%%{}{::location}"
    - "servertype/%%{}{::virtual}"
    - common
  :merge_behavior: deeper
  :yaml:
    :datadir: "/etc/puppet/hieradata"
```

When there is a change in the hiera configuration, we'd like to be able to change it in hiera and then deploy it to our puppet masters.
I'll try to come up with a PR to implement this in `hiera.pp` without breaking your intention to just put it there to shut up Puppet complaining about the missing hiera configuration.

**Comment by tobru** [comment]
I've made a PR #20 which solves the confusing part :smile:
